### ISSUE TITLE
Fix Slack, Discord & WordPress Oauths

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-oauth#1]
The following issues need to be fixed before these oauths can be used.
- [x] Slack connect not working https://github.com/GreenMeteor/humhub-oauth/issues/1#issuecomment-354843486
- [x] Discord error happens on registering a new account
- [x] WordPress malformed url issues.
- [x] WordPress error. https://github.com/GreenMeteor/humhub-oauth/issues/1#issuecomment-359656851

**Comment by Felli** [comment]
### Slack Issue
Need to fix the following code so that it will work
```
protected function initUserAttributes() {
        $params = $$this->getAccessToken()->getParams();
        if (!$params['ok']) {
            throw new \yii\base\InvalidConfigException("Invalid Slack Configuration");
        }
        return $params;
    }
```

**Comment by Felli** [comment]
### WordPress Error
```
yii\authclient\InvalidResponseException: Request failed with code: 400, message: {"error":"invalid_grant","error_description":"Invalid authorization_code."} in /home/greenmet/public_html/community/protected/vendor/yiisoft/yii2-authclient/BaseOAuth.php:210 Stack trace:
#0 /home/greenmet/public_html/community/protected/vendor/yiisoft/yii2-authclient/OAuth2.php(89): yii\authclient\BaseOAuth->sendRequest('POST', 'https://public-...', Array)
#1 /home/greenmet/public_html/community/protected/vendor/yiisoft/yii2-authclient/AuthAction.php(359): yii\authclient\OAuth2->fetchAccessToken('0YjjlRqaCq')
#2 /home/greenmet/public_html/community/protected/vendor/yiisoft/yii2-authclient/AuthAction.php(193): yii\authclient\AuthAction->authOAuth2(Object(humhub\modules\user\authclient\WordPress))
#3 /home/greenmet/public_html/community/protected/humhub/modules/user/authclient/AuthAction.php(35): yii\authclient\AuthAction->auth(Object(humhub\modules\user\authclient\WordPress))
#4 /home/greenmet/public_html/community/protected/vendor/yiisoft/yii2-authclient/AuthAction.php(177): humhub\modules\user\authclient\AuthAction->auth(Object(humhub\modules\user\authclient\WordPress))
#5 [internal function]: yii\authclient\AuthAction->run()
#6 /home/greenmet/public_html/community/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#7 /home/greenmet/public_html/community/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array)
#8 /home/greenmet/public_html/community/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('external', Array)
#9 /home/greenmet/public_html/community/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('user/auth/exter...', Array)
#10 /home/greenmet/public_html/community/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 /home/greenmet/public_html/community/index.php(25): yii\base\Application->run()
#12 {main}

```

**Comment by Felli** [comment]
New issue with Discord oauth, on new account creation an error pops up.
