### ISSUE TITLE
Patreon Error

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-oauth#5]
### What steps will reproduce the problem?
Register your client then setup everything on Patreon's end and after on your end and try to connect to Patreon.

### What is the expected result?
A connection to Patreon

### What do you get instead?
<details>

```
yii\authclient\InvalidResponseException: Request failed with code: 401, message: {"error": "access_denied"} in /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2-authclient/BaseOAuth.php:210 Stack trace:
#0 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2-authclient/OAuth2.php(89): yii\authclient\BaseOAuth->sendRequest('POST', 'https://api.pat...', Array)
#1 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2-authclient/AuthAction.php(359): yii\authclient\OAuth2->fetchAccessToken('rHDkaM1OrLFCC6P...')
#2 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2-authclient/AuthAction.php(193): yii\authclient\AuthAction->authOAuth2(Object(humhub\modules\user\authclient\Patreon))
#3 /home/USER/public_html/SITE/protected/humhub/modules/user/authclient/AuthAction.php(35): yii\authclient\AuthAction->auth(Object(humhub\modules\user\authclient\Patreon)) #4 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2-authclient/AuthAction.php(177): humhub\modules\user\authclient\AuthAction->auth(Object(humhub\modules\user\authclient\Patreon))
#5 [internal function]: yii\authclient\AuthAction->run()
#6 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#7 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array)
#8 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('external', Array)
#9 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('user/auth/exter...', Array)
#10 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 /home/USER/public_html/SITE/index.php(25): yii\base\Application->run()
#12 {main}
```

</details>

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| Oauth version | 1.0.0
| PHP version      | 7.1.13
| Operating system | CloudLinux (CentOS 6)

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
### Error 2
- [x] Fixed
```
yii\authclient\InvalidResponseException: Request failed with code: 301, message: <html> <head><title>301 Moved Permanently</title></head> <body bgcolor="white"> <center><h1>301 Moved Permanently</h1></center> <hr><center>nginx/1.10.1</center> </body> </html> in /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2-authclient/BaseOAuth.php:210 Stack trace:
#0 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2-authclient/OAuth2.php(89): yii\authclient\BaseOAuth->sendRequest('POST', 'https://patreon...', Array)
#1 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2-authclient/AuthAction.php(359): yii\authclient\OAuth2->fetchAccessToken('X5BV37oO6KecCLu...')
#2 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2-authclient/AuthAction.php(193): yii\authclient\AuthAction->authOAuth2(Object(humhub\modules\user\authclient\Patreon))
#3 /home/USER/public_html/SITE/protected/humhub/modules/user/authclient/AuthAction.php(35): yii\authclient\AuthAction->auth(Object(humhub\modules\user\authclient\Patreon))
#4 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2-authclient/AuthAction.php(177): humhub\modules\user\authclient\AuthAction->auth(Object(humhub\modules\user\authclient\Patreon))
#5 [internal function]: yii\authclient\AuthAction->run()
#6 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#7 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array)
#8 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('external', Array)
#9 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('user/auth/exter...', Array)
#10 /home/USER/public_html/SITE/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 /home/USER/public_html/SITE/index.php(25): yii\base\Application->run()
#12 {main}
```

**Comment by Felli** [comment]
Back to the original error in the first post.

**Comment by Felli** [comment]
On-hold till Patron's API isn't changing as much.

/closed till further notice.
